"""Add initial tables

Revision ID: 329703e6e635
Revises: 4f9c28eea2e6
Create Date: 2025-04-23 12:55:40.422934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329703e6e635'
down_revision = '4f9c28eea2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('subscription_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_end', sa.DATETIME(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
