"""Add advantages and disadvantages to Review model

Revision ID: 49d938d144ed
Revises: a788abe47591
Create Date: 2025-04-23 15:08:44.353816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d938d144ed'
down_revision = 'a788abe47591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advantages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disadvantages', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('disadvantages')
        batch_op.drop_column('advantages')

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
