"""Change date field type to String in Review model

Revision ID: 4f9c28eea2e6
Revises: fc1f206145d8
Create Date: 2025-04-23 00:32:39.277756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9c28eea2e6'
down_revision = 'fc1f206145d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=100),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
